package com.fanfan.hotel.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fanfan.hotel.model.ChatMessageBean;
import com.fanfan.hotel.model.NavigationBean;
import com.fanfan.hotel.model.VideoBean;
import com.fanfan.hotel.model.VoiceBean;

import com.fanfan.hotel.db.ChatMessageBeanDao;
import com.fanfan.hotel.db.NavigationBeanDao;
import com.fanfan.hotel.db.VideoBeanDao;
import com.fanfan.hotel.db.VoiceBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatMessageBeanDaoConfig;
    private final DaoConfig navigationBeanDaoConfig;
    private final DaoConfig videoBeanDaoConfig;
    private final DaoConfig voiceBeanDaoConfig;

    private final ChatMessageBeanDao chatMessageBeanDao;
    private final NavigationBeanDao navigationBeanDao;
    private final VideoBeanDao videoBeanDao;
    private final VoiceBeanDao voiceBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatMessageBeanDaoConfig = daoConfigMap.get(ChatMessageBeanDao.class).clone();
        chatMessageBeanDaoConfig.initIdentityScope(type);

        navigationBeanDaoConfig = daoConfigMap.get(NavigationBeanDao.class).clone();
        navigationBeanDaoConfig.initIdentityScope(type);

        videoBeanDaoConfig = daoConfigMap.get(VideoBeanDao.class).clone();
        videoBeanDaoConfig.initIdentityScope(type);

        voiceBeanDaoConfig = daoConfigMap.get(VoiceBeanDao.class).clone();
        voiceBeanDaoConfig.initIdentityScope(type);

        chatMessageBeanDao = new ChatMessageBeanDao(chatMessageBeanDaoConfig, this);
        navigationBeanDao = new NavigationBeanDao(navigationBeanDaoConfig, this);
        videoBeanDao = new VideoBeanDao(videoBeanDaoConfig, this);
        voiceBeanDao = new VoiceBeanDao(voiceBeanDaoConfig, this);

        registerDao(ChatMessageBean.class, chatMessageBeanDao);
        registerDao(NavigationBean.class, navigationBeanDao);
        registerDao(VideoBean.class, videoBeanDao);
        registerDao(VoiceBean.class, voiceBeanDao);
    }
    
    public void clear() {
        chatMessageBeanDaoConfig.clearIdentityScope();
        navigationBeanDaoConfig.clearIdentityScope();
        videoBeanDaoConfig.clearIdentityScope();
        voiceBeanDaoConfig.clearIdentityScope();
    }

    public ChatMessageBeanDao getChatMessageBeanDao() {
        return chatMessageBeanDao;
    }

    public NavigationBeanDao getNavigationBeanDao() {
        return navigationBeanDao;
    }

    public VideoBeanDao getVideoBeanDao() {
        return videoBeanDao;
    }

    public VoiceBeanDao getVoiceBeanDao() {
        return voiceBeanDao;
    }

}
